filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /custodian-output/*.json
    fields:
      service: cloud_custodian
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json
    fields:
      service: wazuh
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["https://${INDEXER_HOST}:${INDEXER_PORT}"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/etc/ssl/root-ca.pem"]
  ssl.certificate: "/etc/ssl/filebeat.pem"
  ssl.key: "/etc/ssl/filebeat.key"

